theme = "redlounge" 
baseurl = "http://vrecan.github.io" 
contentdir = "content" 
layoutdir = "layouts" 
publishdir = "public" 
canonifyurls = false
languagecode = "en-us" 
title = "Vrecan..." 
MetaDataFormat = "toml"
disqusShortname = "vrecan"
[taxonomies]
  category = "categories"
  tag = "tags" 
[author] 
    name = "Ben Aldrich"

[[menu.main]]
    name = "Posts"
    url = "/post"
[[menu.main]]
    name = "About Me"
    url = "/about/about/"

[[menu.social]]
    pre = "<i class='fa fa-github'></i>"
    url = "http://www.github.com/vrecan"
    identifier = "github"

[[menu.social]]
   pre = "<i class='fa fa-google-plus'></i>"
   url = "http://google.com/+BenAldrich"
   identifier = "google-plus"
